version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27018:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: junaid
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
    - ./mongo-data:/data/db

  nodeapp:
    build: .
    restart: always
    container_name: chaicode-app
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    depends_on:
      - mongo
