name: Build and Push Docker image

on:
  push:
    branches:
      - main   # or master, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chaicode:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chaicode:latest
